# Generated by Django 4.1.5 on 2023-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile_second_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='D:\\project1\\Personalized_meal_recommendation_system-master\\DJANGO\\minor\\media\\website\\images\\avatar.jpg', upload_to='website/images'),
        ),
    ]
